obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.15
inflation_radius: 0.15
#max_obstacle_height: 0.6
#min_obstacle_height: 0.0
#obstacles:
observation_sources: scan
scan: {data_type: LaserScan, expected_update_rate: 0.4,
  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
#:scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
